[[meetups]]
id = 0
title = "Opensource Contributions Meetup"
date = "11.02.2026"
description = "In this meetup we will contribute to or create opensource software as teams, you will get support in doing so"
markdown_name = "opensource_0.md"

[meetups.address]
street = "Barf√ºsserplatz 6"
city = "Basel"
postal_code = "4051"
country = "Switzerland"
description = "Optravis Headquarter - Level 4"

[[meetups.sponsors]]
name = "Optravic LLC"
website = "http://optravis.com"
content = ""
